title: Configuratie
data:
  company_name: 'Lekker bezig schiedam'
  copyright_since: 2024
  copyright_name: 'Sportverkiezingen 2024'
  privacy_statement_type: pdf
  privacy_statement_asset: privacyverklaring.pdf
  header_logo: logos/lekker-bezig-logo.png
  header_logo_mh: 170
  header_logo_mh_mob: 64
  header_height: 230
  header_height_mob: 94
  header_bg_c: '#383887'
  header_b_c: '#faed45'
  header_hb_c: '#f04f4d'
  header_link_c: '#ffffff'
  header_link_hc: '#faed45'
  header_bg_c_menu: '#383887'
  header_link_c_menu: '#ffffff'
  footer_logo: logos/lekker-bezig-logo-footer.png
  footer_logo_mw: 300
  footer_logo_mw_mob: 200
  footer_bg_c: '#383887'
  footer_text_c: '#ffffff'
  footer_text_hc: '#FAED45'
  footer_x_c: '#ffffff'
  footer_x_hc: '#FAED45'
  footer_fb: 'https://www.facebook.com/lekkerbezigschiedam/'
  footer_fb_c: '#ffffff'
  footer_fb_hc: '#FAED45'
  footer_ig: 'https://www.instagram.com/lekkerbezigschiedam/'
  footer_ig_c: '#ffffff'
  footer_ig_hc: '#FAED45'
  footer_yt: 'https://www.youtube.com/@lekkerbezigschiedam3896/videos'
  footer_yt_c: '#ffffff'
  footer_yt_hc: '#FAED45'
  form_hc: '#383887'
  form_ec: '#ffffff'
  form_sc: '#428959'
  form_logo: logos/lekker-bezig-logo.png
  font_import: cdn.esens.nl/fonts/neusa_next/font.css
  font_family_body: "'NeusaNextBold'"
  font_family_head: "'NeusaNextBold'"
  font_h1: 72
  font_h1_m: 42
  font_h2: 36
  font_h2_m: 26
  font_h3: 36
  font_h3_m: 26
  font_h4: 28
  font_h4_m: 24
  font_body: 24
  font_body_m: 16
  font_body_c: '#fff'
  font_head_c: '#fff'
  font_link_c: '#fff'
  font_link_hc: '#faed45'
  font_underline_h: false
  cookie_primary_color: '#ffffff'
  cookie_toggle_color: '#228B22'
  html_root_size: 16
  max_width: 1520
  padding: 24
  gutters_xs: 8
  gutters_sm: 16
  gutters_md: 24
